name: atg
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_social_button: ^1.1.6+1
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.9
  lucide_icons: ^0.257.0
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.5.4
  share_plus: ^10.1.4
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# âœ… ONLY ONE flutter_launcher_icons BLOCK
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splash.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/pos5.PNG
    - assets/images/profile1.jpeg
    - assets/images/profile.jpeg
    - assets/images/digi.jpg
    - assets/images/logo.jpeg
    - assets/logo.png
    - assets/images/splash.jpeg
